version: '3'
services:
  custom_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"
      - "8000:8000"
    expose:
      - "9000"
      - "8000"
    environment:
      - "PORT=8080"
      - "CONFIG_SERVER_URI=${CONFIG_SERVER_URI}"
      - "EUREKA_SERVER=${EUREKA_SERVER}/eureka/"
      - "MANAGE_PORT=8000"
      - "TZ=Europe/Moscow"
